38 add markdown pitch and media into creating fundraising form (#40)
* send media and logo data to backend

* create business and image in db

* add markdown editor

* save to db

* update navbar

* update business request button

* add markdown rendering and edit image

* reformat

* edit business detail page

diff --git a/.github/workflows/test_build.yml b/.github/workflows/test_build.yml
--- a/.github/workflows/test_build.yml
+++ b/.github/workflows/test_build.yml
@@ -43,7 +43,12 @@ jobs:
       - name: Install dependencies
         run: pnpm install
       - name: Build with Next.js
-        run: pnpm next build
+        run: |
+          pnpm next build
+          if [ $? -ne 0 ]; then
+            echo "Build failed"
+            exit 1
+          fi
         env:
           POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
           POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
